* Interleaved Textbooks?

Some history, what this is all about...

In the past, textbooks were sometimes published as /interleaved/ editions. That meant, each page was followed
by a blank page and ambitious students/scholars had the ability to take their notes directly in their copy of
the textbook. Newton and Kant were prominent representatives of this technique [fn:blumbach].

Nowadays textbooks (or lecture material) come in PDF format. Although almost every PDF Reader has the ability
to add some notes to the PDF itself, it is not as powerful as it could be. This is what this [[https://www.gnu.org/software/emacs/][Emacs]] minor mode
tries to accomplish. It presents your PDF side by side to an [[http://orgmode.org][Org Mode]] buffer with you notes. Narrowing down to
just those passages that are relevant to this particular page in the document viewer.

In a later step it should be possible to create truly /interleaved/ PDFs of your notes.

* Installation
This item is my fork on [[https://github.com/rudolfochrist/interleave][interleave]], but this using [[https://github.com/manateelazycat/emacs-application-framework][EAF]] open the PDF file.

#+begin_src
(use-package interleave
  :ensure nil
  :quelpa (interleave :fetcher github :repo "luhuaei/interleave")
  :diminish interleave-pdf-mode interleave-mode
  :bind (:map interleave-mode-map
         ("M-." . 'interleave-sync-pdf-page-current)
         ("M-p" . 'interleave-sync-pdf-page-previous)
         ("M-n" . 'interleave-sync-pdf-page-next)
         :map interleave-pdf-mode-map
         ("C-c M-i" . 'interleave-add-note)
         ("C-c M-o" . 'interleave-open-notes-file-for-pdf)
         ("C-c M-q" . 'interleave-quit))
  :config
  (setq interleave-org-notes-dir-list '("~/org/interleave/")
  (setq interleave-split-direction 'vertical)
  (setq interleave-disable-narrowing t)
  (setq interleave-split-lines 20))
#+end_src

* Usage
Create a Org file that will keep your notes. In the Org header section (=#+TITLE=, =#+AUTHOR=, etc.) add

#+BEGIN_SRC
#+INTERLEAVE_PDF: /the/path/to/pdf.pdf
#+END_SRC

Then you can start *interleave* by typing

#+BEGIN_SRC
M-x interleave-mode
#+END_SRC

The split direction is determined by the customizable variable =interleave-split-direction=. When
=interleave-mode= is invoked with a prefix argument the inverse split direction is used e.g. if
=interleave-split-direction= is set to =vertical= the buffer is split horizontally.

** Multi-PDF Notes

Normally the notes/PDF relation is bidirectional. This means for every PDF there is one notes file. But it is
also possible to keep a single notes file for multiple PDFs.

To keep a multi-PDF notes file create a headline for each PDF and set the =INTERLEAVE_PDF= property on it.

: * Notes for CS103
:   :PROPERTIES:
:   :INTERLEAVE_PDF: cs103.pdf
:   :END:

To use =interleave-mode= on this headline, simply place your point onto the headline an type

: M-x interleave-mode RET

to start =interleave-mode= for this subtree.

*Notice that you have to decide. It is not possible to keep multi-PDF and normal notes in the same file.*

* Footnotes
[fn:blumbach] For some more information see: [[http://takingnotenow.blogspot.de/2008/07/note-keeping-in-1786-blumenbachs-system.html]]
